In [1]:
import numpy as np

arange

In [2]:
arr=[1,2,3,4,5,6,7,8,9]

In [3]:
arr_np = np.array(arr)

In [4]:
arr_np

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr=np.arange(1,9+1)

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr=np.arange(start=1,stop=9+1)

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr_reverse=np.arange(stop=9+1,start=1)

In [10]:
arr_reverse

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr=np.arange(0,9+1,2)

In [12]:
arr

array([0, 2, 4, 6, 8])

In [13]:
arr=np.arange(start=0,stop=10,step=2)

In [14]:
arr

array([0, 2, 4, 6, 8])

In [15]:
arr_sample = np.arange(0,5,0.5)

In [16]:
arr_sample

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [17]:
arr=np.array([2,5,3,10,9,4,1,8,6,7])

In [18]:
arr

array([ 2,  5,  3, 10,  9,  4,  1,  8,  6,  7])

In [19]:
arr[3]

10

In [20]:
np.sort(arr) # 비파괴적 함수

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.sort(arr)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [22]:
arr2=np.sort(arr)

In [23]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr2d=np.array([[5,6,7,8],
              [4,3,2,1],
              [10,12,9,11]])

In [25]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10, 12,  9, 11]])

In [26]:
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10, 12,  9, 11]])

In [27]:
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

argsort : 정렬된 값을 반환하지 않음,index를 반환

In [34]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10, 12,  9, 11]])

In [35]:
np.argsort(arr2d,axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [2, 0, 3, 1]], dtype=int64)

In [30]:
arr2d_1 = np.array([[5,6,7,8],
              [4,3,2,1],
              [13,16,15,14],
              [10,12,9,11]])

In [31]:
np.argsort(arr2d_1,axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [0, 3, 2, 1],
       [2, 0, 3, 1]], dtype=int64)

In [32]:
np.sort(arr2d_1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12]])