In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],
           [4,5,6]])
b=np.array([[4,5,6],
           [1,2,3]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b

array([[4, 5, 6],
       [1, 2, 3]])

In [6]:
a+b

array([[5, 7, 9],
       [5, 7, 9]])

In [7]:
a-b

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [8]:
a*b

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [9]:
a/b

array([[0.25, 0.4 , 0.5 ],
       [4.  , 2.5 , 2.  ]])

In [13]:
a.shape

(2, 3)

In [14]:
b.shape

(2, 3)

In [15]:
c=np.array([[1,2],[3,4],[5,6]])

In [16]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a+c

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

sum

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.sum(a,axis=0)

array([5, 7, 9])

In [12]:
np.sum(a,axis=1)

array([ 6, 15])

곱셈

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b

array([[4, 5, 6],
       [1, 2, 3]])

In [20]:
a*b

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [21]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [22]:
a.shape

(3, 3)

In [23]:
b.shape

(3, 2)

In [24]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [25]:
1*1 + 2*3 + 3*5

22

In [26]:
1*2 + 2*4 + 3*6

28

In [29]:
2*1 + 3*3 + 4*5

31

In [30]:
2*2 + 3*4 + 4*6

40

brodcasting

In [31]:
a=np.array([[1,2,3],[4,5,6]])

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [34]:
a - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [35]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [37]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [38]:
b=np.array([[1],[2]]) 

In [39]:
a.shape, b.shape

((2, 3), (2, 1))

In [41]:
a*b # 행별 로 곱적용

array([[ 1,  2,  3],
       [ 8, 10, 12]])