numpy: 수학, 과학용 계산을 돕기위해 만들어진 라이브러리

In [3]:
import numpy as np

ndarray 생성하기

In [7]:
a_list=[1, 2.15, '가나다', '123']
a_list

[1, 2.15, '가나다', '123']

In [8]:
arr=np.array([1,2,3,4], dtype=int)
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

list

list를 이용해 ndarray 생성하기

In [10]:
my_list1=[1,2,3,4,5]

In [11]:
arr1=np.array(my_list1)

In [12]:
arr1

array([1, 2, 3, 4, 5])

In [13]:
arr1.dtype

dtype('int32')

In [14]:
my_list2 = [[1,2,3],[4,5,6]]

In [15]:
arr2=np.array(my_list2)

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr1.shape

(5,)

In [18]:
arr2.shape

(2, 3)

array는 list와 다르게 하나의 단일 데이터 타입만을 허용

In [19]:
arr=np.array([1,2,3,4.15])

In [20]:
arr.dtype

dtype('float64')

In [21]:
arr

array([1.  , 2.  , 3.  , 4.15])

In [26]:
arr=np.array([1,2,3,4.15], dtype=int)

In [27]:
arr

array([1, 2, 3, 4])

In [28]:
arr=np.array([1,2,4.15,'가나다','1234'])

In [29]:
arr

array(['1', '2', '4.15', '가나다', '1234'], dtype='<U32')

In [30]:
arr.dtype

dtype('<U32')

In [32]:
arr=np.array([1,2,4.15,'1234'], dtype=int)

In [33]:
arr

array([   1,    2,    4, 1234])

In [34]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [35]:
arr.shape

(10,)

In [36]:
list_a = [0,1,2,3,4,5,6,7,8,9]

In [37]:
print(list_a[3])

3


In [40]:
arr[-1]

9

In [41]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [42]:
arr2.shape

(3, 4)

In [43]:
arr2[0,1]

2

In [44]:
arr2[2,2]

11

In [46]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[:4+1]

array([0, 1, 2, 3, 4])

In [48]:
arr[2:4+1]

array([2, 3, 4])

In [49]:
arr2[1,:]

array([5, 6, 7, 8])

In [51]:
arr2[1,1:3]

array([6, 7])

In [52]:
arr2[:,3]

array([ 4,  8, 12])

In [53]:
arr2[:1+1,[1,3]]

array([[2, 4],
       [6, 8]])

In [54]:
arr=np.array([12,423,2,75,234,54,11,423,13])

In [55]:
my_index=[1,4,5]

In [56]:
arr[my_index]

array([423, 234,  54])

In [57]:
arr2[[0,2],:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [58]:
arr2[:,[0,1,3]]

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [59]:
arr=np.array([1,2,3,4,5])

In [60]:
bool_list=[True,False,True]

In [61]:
arr[bool_list]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3

In [63]:
bool_list1=[True,True,False,True,False]

In [64]:
arr[bool_list1]

array([1, 2, 4])

In [65]:
bool_array=np.array([[True,True,False,False],[True,False,True,False],[True,True,False,True]])

In [66]:
arr2[bool_array]

array([ 1,  2,  5,  7,  9, 10, 12])

In [69]:
arr2[arr2%3==2]

array([ 2,  5,  8, 11])