In [2]:
import numpy as np

In [3]:
arr2d_1 = np.array([[5,6,7,8],
              [4,3,2,1],
              [13,16,15,14],
              [10,12,9,11]])

In [4]:
arr2d_1

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [13, 16, 15, 14],
       [10, 12,  9, 11]])

In [5]:
np.argsort(arr2d_1,axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [0, 3, 2, 1],
       [2, 0, 3, 1]], dtype=int64)

In [8]:
arr2d_1 = np.array([[0,1,2,3],
              [3,2,1,0],
              [0,3,2,1],
              [2,3,0,1]])

In [9]:
np.argsort(arr2d_1,axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [0, 3, 2, 1],
       [2, 3, 0, 1]], dtype=int64)